uktrade/update-supply-chain-information

- Makefile
- README.md
- api/api/fixtures.json
This PR adds fixtured to the database. It adds government departments, strategic actions, and supply chains. This will allow us to be able to load some initial data when creating the front end of the project.
> Add fixtures to the project

- defend_data_capture/accounts/auth.py
We found a bug that prevented the authentication of a user if they had not been previously signed in on Staff SSO on another tool. Essentially, the code was checking for a `gov_department_id` before applying one. 
The code has now been amended to check for and apply a `gov_department_id` before authenticating. 
To check this, in an incognito Chrome browser: 
spin up the project and visit localhost:8000
You should be redirected through the standard Staff SSO sign up method,
following the completion of that, you should be redirected back to the landing page.
> Amend CustomAuthbrokerBackend class to fix auth bug

- defend_data_capture/supply_chains/test/test_taskcomplete_view.py
- defend_data_capture/supply_chains/test/test_tasklist_view.py
- defend_data_capture/supply_chains/views.py
This PR brings changes for [RT-167](https://uktrade.atlassian.net/browse/RT-167)
**Changes**
- Inherit _GovDepPermissionMixin_ for Tasklist and updateComplete views
- Update tests to reflect above.
> RT-167: Add permission check for Tasklist and UpdateComplete View

- cypress/integration/home_page_spec.js
- defend_data_capture/supply_chains/templates/index.html
- defend_data_capture/supply_chains/test/test_views.py
- defend_data_capture/supply_chains/views.py
This PR only includes first part of [RT-170](https://uktrade.atlassian.net/browse/RT-170). Additional changes will be worked within [RT-195](https://uktrade.atlassian.net/browse/RT-195)
**Changes**
- Change the Date format to DD/MM/YYYY
- Update changes from design document and tests
**Screenshot**
> RT-170: Change Date format in HomePage

- cypress/fixtures/strategicActionUpdates.json
- cypress/fixtures/strategicActions.json
- cypress/fixtures/supplyChains.json
- cypress/integration/sau_review_spec.js
- cypress/support/utils.js
- defend_data_capture/defend_data_capture/urls.py
- defend_data_capture/supply_chains/templates/sau_review.html
- defend_data_capture/supply_chains/test/test_taskcomplete_view.py
- defend_data_capture/supply_chains/test/test_update_review.py
- defend_data_capture/supply_chains/views.py
Brings changes for [RT-191](https://uktrade.atlassian.net/browse/RT-191)
**Changes**
- Create view _SAUReview_ to render the submitted update
- Tests for above
- Manual timeline fix for fixtures
**Screenshot**
> RT-191: Create SAU review page

- cypress/integration/monthly_update_forms_no_completion_date_spec.js
- cypress/integration/monthly_update_forms_with_completion_date_spec.js
- cypress/integration/sau_review_spec.js
- cypress/integration/sc_summary_spec.js
- cypress/integration/strategic_action_summary_spec.js
- cypress/integration/task_complete_spec.js
- cypress/integration/task_list_spec.js
- defend_data_capture/defend_data_capture/urls.py
- defend_data_capture/supply_chains/templates/index.html
- defend_data_capture/supply_chains/templates/sau_review.html
- defend_data_capture/supply_chains/templates/sc_summary.html
- defend_data_capture/supply_chains/templates/strategic_action_summary.html
- defend_data_capture/supply_chains/templates/supply_chains/monthly_update_info_form.html
- defend_data_capture/supply_chains/templates/supply_chains/monthly_update_revised_timing_form.html
- defend_data_capture/supply_chains/templates/supply_chains/monthly_update_status_form.html
- defend_data_capture/supply_chains/templates/supply_chains/monthly_update_summary.html
- defend_data_capture/supply_chains/templates/supply_chains/monthly_update_timing_form.html
- defend_data_capture/supply_chains/templates/task_complete.html
- defend_data_capture/supply_chains/templates/task_list.html
- defend_data_capture/supply_chains/test/test_monthly_update_views_user_journey.py
- defend_data_capture/supply_chains/test/test_sc_summary_view.py
- defend_data_capture/supply_chains/test/test_taskcomplete_view.py
- defend_data_capture/supply_chains/test/test_tasklist_view.py
- defend_data_capture/supply_chains/test/test_update_review.py
- defend_data_capture/supply_chains/test/test_views.py
- defend_data_capture/supply_chains/views.py
Apart from rearranging `urls.py` to make it easier to add more URLs in the future, the main changes are to ensure all URLs end in a / and a couple of minor changes to path components to better reflect the content or purpose of the associated resource.
> Tidy up URLconfigs.

- cypress/integration/noindex_nofollow_spec.js
- defend_data_capture/supply_chains/templates/base.html
Ref. "Indexing" at https://readme.trade.gov.uk/docs/procedures/1st-go-live.html?highlight=indexing#operations
> RT-226: Prevent indexing.

- LICENSE
Adding MIT license as per https://readme.trade.gov.uk/docs/procedures/open-sourcing.html
> RT-253: Create LICENSE

- defend_data_capture/defend_data_capture/settings.py
- defend_data_capture/sample.env
https://uktrade.atlassian.net/browse/RT-282?atlOrigin=eyJpIjoiNjJmMDZiMzc4ODFhNDNjZjljOGM0ODBjYzI1M2Y3MTQiLCJwIjoiaiJ9
> RT-282: Require `DEBUG` to be enabled by the environment.

- package-lock.json
- package.json
- requirements.txt
This PR combines the updates raised by dependebot in PRs: #75, #76, #77, #79, #80, #81.
I have merged the updates into one PR to avoid having to merge/rebase 5 times.
> Update dependencies with security vulnerabilities

- .locust.conf
- README.md
- load_test/locustfile.py
- requirements.txt
**Changes**
- Adding locust related packages to app's env
- Create load test tool config and scenario file
- Update README
> RT-307: Feature/load test

- cypress.json
- run_functional_tests.sh
- update_supply_chain_information/supply_chains/test/test_views.py
- update_supply_chain_information/supply_chains/views.py
- update_supply_chain_information/test_settings.py
Continuation of #117 
**Changes**
- Include archive flag while counting number of SA's within HomePageView
- Test to catch related errors
- Refactor env var _FEEDBACK_GROUP_EMAIL_ to respective modules away from _run_funcationl_test.sh_ so that tests can be run in different configuration
> RT-337: Handling archived objects

- cypress/integration/monthly_update_forms_no_completion_date_spec.js
- cypress/integration/monthly_update_forms_with_completion_date_spec.js
- update_supply_chain_information/supply_chains/models.py
- update_supply_chain_information/supply_chains/templates/supply_chains/includes/existing_completion_date.html
> RT-342: Implement changes to current/changed completion date display in monthly update forms

- update_supply_chain_information/supply_chains/admin.py
- update_supply_chain_information/supply_chains/models.py
**Changes**
- Include requested fields/columns to Admin view of models
- Simplify string representation of models
> RT-299: Feature/admin UI changes

- cypress/integration/strategic_action_summary_spec.js
- cypress/support/utils.js
- update_supply_chain_information/assets/stylesheets/supply_chain.scss
- update_supply_chain_information/supply_chains/templates/includes/sa_info_list.html
- update_supply_chain_information/supply_chains/templates/strategic_action_summary.html
Refactoring work related to RT-356 per latest design
**Changes**
- Re-introduce _change_ link for edit functionality
- Update breadcrumbs(ie excluding current page)
**Note**
Some of the links within this PR is temporary/hard coded as design is still being worked on.
> RT-80: Refactor/sa summary

- cypress/integration/access_denied_spec.js
- cypress/integration/privacy_notice_spec.js
- cypress/integration/sau_review_spec.js
- cypress/integration/sc_home_page_spec.js
- cypress/integration/sc_summary_spec.js
- cypress/integration/strategic_action_summary_spec.js
- cypress/integration/task_complete_spec.js
- cypress/integration/task_list_spec.js
- cypress/support/utils.js
- update_supply_chain_information/config/urls.py
- update_supply_chain_information/supply_chains/admin.py
- update_supply_chain_information/supply_chains/templates/403.html
- update_supply_chain_information/supply_chains/templates/privacy_notice.html
- update_supply_chain_information/supply_chains/templates/sau_review.html
- update_supply_chain_information/supply_chains/templates/sc_home.html
- update_supply_chain_information/supply_chains/templates/sc_summary.html
- update_supply_chain_information/supply_chains/templates/strategic_action_summary.html
- update_supply_chain_information/supply_chains/templates/task_complete.html
- update_supply_chain_information/supply_chains/templates/task_list.html
- update_supply_chain_information/supply_chains/test/test_admin.py
- update_supply_chain_information/supply_chains/test/test_middleware.py
- update_supply_chain_information/supply_chains/test/test_views.py
**Changes**
- Update Home within breadcrumbs to point to new homepage
- Remove current page from breadcrumbs list
- Move route for _PrivacyView_ to top level
> RT-379: Feature/homepage links

- update_supply_chain_information/supply_chains/templates/base.html
- update_supply_chain_information/supply_chains/templates/common_base.html
Work related to RT-389 and #147 
**Changes**
- Create a new template _common_base_ to be used across resilience tools(Forms and Visualisations)
> RT-389: Creating common_base template to be used across resilience tools

- update_supply_chain_information/activity_stream/serializers.py
Suggested by Michal when reviewing the Activity Stream and Data Flow aspects of the pipeline.
> RT-404: Change app name in serialisation.

- cypress/fixtures/user.json
- cypress/integration/home_page_spec.js
- cypress/integration/not_found_spec.js
- cypress/integration/sap_filters_spec.js
- cypress/support/utils.js
- update_supply_chain_information/accounts/models.py
- update_supply_chain_information/accounts/test/factories.py
- update_supply_chain_information/action_progress/admin.py
- update_supply_chain_information/action_progress/apps.py
- update_supply_chain_information/action_progress/forms.py
- update_supply_chain_information/action_progress/models.py
- update_supply_chain_information/action_progress/templates/action_progress_base.html
- update_supply_chain_information/action_progress/templates/action_progress_dept.html
- update_supply_chain_information/action_progress/templates/action_progress_sc.html
- update_supply_chain_information/action_progress/templatetags/sap_tags.py
- update_supply_chain_information/action_progress/test/test_sap_filters.py
- update_supply_chain_information/action_progress/test/test_sap_form.py
- update_supply_chain_information/action_progress/tests.py
- update_supply_chain_information/action_progress/views.py
- update_supply_chain_information/config/settings.py
- update_supply_chain_information/config/urls.py
- update_supply_chain_information/supply_chains/templates/404.html
- update_supply_chain_information/supply_chains/templates/index.html
- update_supply_chain_information/supply_chains/templatetags/supply_chain_tags.py
**Changes**
- New app *action_progress* added to implement SAP details
- Created Base and couple of derived classes to implement required view with 2 nested filters and a Form
- Tests
- Inclusion of custom *404* page
**Screenshots**
> RT-435: Feature/sap filters

- cypress/fixtures/strategicActions.json
- cypress/integration/sap_listing_spec.js
- cypress/integration/sau_review_spec.js
- update_supply_chain_information/action_progress/templates/action_progress_list.html
- update_supply_chain_information/action_progress/templates/action_progress_sc.html
- update_supply_chain_information/action_progress/templates/includes/tabbed_action_list.html
- update_supply_chain_information/action_progress/test/test_sap_list.py
- update_supply_chain_information/action_progress/views.py
- update_supply_chain_information/assets/stylesheets/supply_chain.scss
- update_supply_chain_information/config/urls.py
**Changes**
- Renamed view class to ActionProgressListView and template
- Implement listing
- Tests
- Unrelated change: To include check for _user.is_authenticated_ for UserPassesTestMixin
**Screenshot**
> RT-392: SAP listing

- cypress/integration/sap_filters_spec.js
- cypress/integration/sap_listing_spec.js
- update_supply_chain_information/action_progress/forms.py
- update_supply_chain_information/action_progress/templates/action_progress_base.html
- update_supply_chain_information/action_progress/templates/action_progress_dept.html
- update_supply_chain_information/action_progress/templates/action_progress_list.html
- update_supply_chain_information/supply_chains/models.py
**Changes**
- Content update, mainly
> RT-473: Refactor/sap updates

- update_supply_chain_information/supply_chains/models.py
- update_supply_chain_information/supply_chains/test/test_sau_model.py
Bug fix monthly updates from admin panel
> RT-489: SAU validation for updates must cover the whole period

- cypress/integration/banner_spec.js
- update_supply_chain_information/assets/stylesheets/application.scss
- update_supply_chain_information/supply_chains/templates/base.html
- update_supply_chain_information/supply_chains/templates/common_base.html
- update_supply_chain_information/supply_chains/templatetags/supply_chain_tags.py
- update_supply_chain_information/supply_chains/test/test_monthly_updates_at_month_transition.py
**Changes**
- Base template now has navigation links
- New tag _get_active_menu_ has been added for styling the current app
- Tests
**Screenshots**
> RT-441: Feature/banner update

- update_supply_chain_information/accounts/test/test_auth.py
See issue #231.
There are two tests, one for now, one for later:
The `accounts.test.test_auth.test_two_departments_with_same_email_domain_prevents_login` test will pass while this issue is unresolved. It should be marked as expected to fail once the issue is resolved.
The `accounts.test.test_auth.test_two_departments_with_same_email_domain_does_not_prevent_login` test will pass when this issue has been resolved. It is currently marked as expected to fail.
> Test for expected user creation failure when multiple departments share email domains

- cypress/integration/scd_info_spec.js
- cypress/integration/scd_listing_spec.js
- update_supply_chain_information/chain_details/templates/chain_details_info.html
- update_supply_chain_information/chain_details/templates/chain_details_list.html
- update_supply_chain_information/chain_details/test/test_scd_info.py
- update_supply_chain_information/chain_details/views.py
- update_supply_chain_information/config/urls.py
**Changes**
- New URL and view for SupplyChain details info
- Update link from listing page
- Tests
> RT-479: Feature/scd details

- cypress/integration/banner_spec.js
- cypress/integration/home_page_spec.js
- update_supply_chain_information/supply_chains/templates/base.html
- update_supply_chain_information/supply_chains/templates/index.html
**Changes**
- Add/Include 2 QS links to banner
- Add 2 QS links to homepage listing
> RT-440: Adding qs links to banner and homepage

- package.json
> RT-612: Upgrade node to 14.17.6

- Makefile
- README.md
Some small changes from when I first tried spinning this up to familiarise myself with the application before trying to migrate it from Gov PaaS.
> Improve reliability of spinning it up first time locally

- requirements.in/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/prod.txt
> Security - TSS-832 - Django upgrade

- requirements.in/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/prod.txt
Reverts uktrade/update-supply-chain-information#367.
Accidentally downgraded a bunch of packages.
> Revert "Security - TSS-832 - Django upgrade"
