uktrade/update-supply-chain-information

api/api/supply_chain_update/serializers.py, api/api/supply_chain_update/test/factories.py, api/api/supply_chain_update/test/test_views.py, api/api/supply_chain_update/views.py, api/api/urls.py
This PR adds an endpoint allowing CRUD operations on the `StrategicAction` model. It also includes a filter on the view which allows a `supply_chain_id` query parameter to be passed to the endpoint (`/strategic-actions?supply_chain_id=XXX`) which will just return strategic actions linked to that supply chain.
The tests I have included represent what this endpoint will be used for in our first feature, which will be a user giving a monthly update for a strategic action. However, any suggestions on additional necessary tests are very welcome!
=> Add strategic action endpoint

api/api/supply_chain_update/serializers.py, api/api/supply_chain_update/test/test_views.py, api/api/supply_chain_update/views.py, api/api/urls.py
This PR adds an endpoint with CRUD operations on the SupplyChain model. It also includes a filter on the view which allows a `gov_department_id` parameter to be passed to the endpoint (/supply-chains?gov_department_id=XXX) which will just return supply chains linked to that government department. An annotation has also been added to return the number of strategic actions linked to a supply chain, on each returned supply chain object.
The tests included check the basics of the route. Please let me know if you have any suggestions for how I can make this code better though! 🎉
=> Add supply chain end point

api/api/supply_chain_update/test/test_views.py, api/api/supply_chain_update/views.py
This PR adds a filter to the `/strategic-actions` endpoint, allowing additional filtering for archived/unarchived actions. It also includes a filter on the view which allows a supply_chain_id query parameter to be passed to the endpoint (/strategic-actions?supply_chain_id=XXX&is_archived=true/false) which will just return strategic actions linked to that supply chain,  if they are archived or not.
Tests have been added or amended to cater for this filtering but additional test suggestions are very welcome 😄
=> Add filter to the strategic-actions endpoint to allow filtering by is_archived

api/api/supply_chain_update/serializers.py, api/api/supply_chain_update/test/factories.py, api/api/supply_chain_update/test/test_views.py, api/api/supply_chain_update/views.py, api/api/urls.py, api/conftest.py
This PR adds an API endpoint `strategic-action-updates` to perform CRUD operations on the `StrategicActionUpdate` model. It allows two filters which can be applied to get requests:
- Filtering by `strategic_action_id`, which will get all updates related to a strategic action
- Filtering by `is_submitted`, which when true will only return updates with a status of `submitted`, and when false will return updates with a status of either `in_progress` or `completed`. This distinction is to allow users to update non-submitted updates.
=> Add endpoint for strategic action updates

Makefile, README.md, api/api/settings.py, api/requirements.txt, api/sample.env, docker-compose.yaml
This PR sets the default database for the API as a postgres db and allows it to be run in docker. It also includes:
- a makefile with commands to create and drop the db in docker
- a db url in the sample.env
=> Switch database to postgres and run in docker

defend_data_capture/requirements.txt
This PR updates the Django dependency, as advised by a security warning from Github. 
Here's the link to the security update : https://www.djangoproject.com/weblog/2021/feb/01/security-releases/
=> Update Django dependency to fix security issue

Makefile
Fix Makefile errors on some of the targets, refer #21 
**Changes**
- Use _docker-compose_ to reference a container instead of _docker_. Docker commands require name of the container as an argument which is not a constant
=> #21: Using docker-compose to refer container instance within Makefile

defend_data_capture/requirements.txt
This PR updates the dependency `urllib` as Dependabot has flagged the previous version as having a security vulnerability ([here](https://github.com/uktrade/defend-data-capture/security/dependabot)).
=> Update urllib3 package due to security vulnerability

Makefile, README.md
This PR updates makes the following changes to the commands in the Makefile:
- Separates out the `setup-db` command into `setup-db` and `create-db` - to enable developers to apply migrations and load fixtures when the `defend` database already exists
- Adds the `load-data` command into the `setup-db` command, given that the DIT `gov_department` fixture is necessary for the app to run with staff SSO
It also adds the following details to the Readme:
- How to set the needed environment variables
- To only access the application on localhost:8000
=> Update make commands and readme

README.md, package-lock.json, package.json
In the previous PR (#27) I accidentally included an older version of Webpack. 
This PR updates webpack to the latest version - `^5.31.2` and adds the `--mode development` flag to the webpack command which has been introduced since the previous version. 
This should address this security vulnerability raised by dependabot - https://github.com/uktrade/defend-data-capture/security/dependabot
I have also corrected the readme instructions, as the `--watch` flag is already applied to the `npm run dev` command.
=> Update webpack version

.gitignore, README.md, cypress/integration/home_page_spec.js, cypress/plugins/index.js, cypress/support/index.js, defend_data_capture/supply_chains/templates/base.html, defend_data_capture/supply_chains/templates/index.html, package-lock.json, package.json
This PR adds the [cypress-axe package](https://github.com/component-driven/cypress-axe) with its dependency axe-core to the repository to allow for automated accessibility testing, and adds a test for accessibility issues to the home page spec. 
I am adding this to the repository now, so that accessibility issues can be addressed whilst building, rather than retrospectively. 
1. Add the command `cy.injectA11y()` after wherever `cy.visit(url)` is called. This injects the `axe-core` runtime into the page being tested.
2. Add a test to check for accessibility which includes the command `cy.runA11y()`. This is a custom command which will output details of any accessibility violations into a table in the terminal where cypress is running, as in the screenshot below. I added a separate table …
=> Add automated accessibility tests

.github/workflows/run-tests.yaml, .gitignore, Makefile, cypress.json, defend_data_capture/defend_data_capture/settings.py, run_functional_tests.sh
This PR adds a github action to run both the unit and functional tests against all pull requests.
It also includes some tweaks to existing commands to make them run more efficiently (and therefore the action quicker) including:
- Not saving the video which cypress records of the functional tests if they pass
- Only killing the pid process and dropping the test database table when running the functional tests locally
- Only bringing up the db container in docker apart from in when running the functional tests (which also need the mock-sso container)
I have also provided defaults for the settings which take their values from environment variables, which avoids the need to set them as blank values for running the unit tests, as they are not needed for these tests.
I had planned to have two …
=> Add github action for running unit tests

cypress.json, cypress/fixtures/strategicActions.json, cypress/integration/strategic_action_summary_spec.js, cypress/integration/task_list_spec.js, defend_data_capture/conftest.py, defend_data_capture/defend_data_capture/urls.py, defend_data_capture/supply_chains/templates/includes/pagination.html, defend_data_capture/supply_chains/templates/index.html, defend_data_capture/supply_chains/templates/strategic_action_summary.html, defend_data_capture/supply_chains/templates/task_list.html, defend_data_capture/supply_chains/test/factories.py, defend_data_capture/supply_chains/test/test_utils.py, defend_data_capture/supply_chains/test/test_views.py, defend_data_capture/supply_chains/utils.py, defend_data_capture/supply_chains/views.py
This PR adds the 'Strategic action summary page', which displays details of all the active (i.e un-archived) strategic actions linked to a given supply chain. [Design here](https://xd.adobe.com/view/9a58e0ae-80ef-48cb-88b2-150c67f2b659-cf0b/screen/1da20235-b93f-4438-a343-f49d2a8f9939)
**User flow**
- User visits `/supply-chain/strategic-actions` from clicking the 'Strategic action summary' link on the task list page
- User sees a paginated list of all unarchived strategic actions for that supply chain
- User can see details of a strategic action by clicking either the action name or the + symbol
- (Not covered in this PR) User can click the 'change' link next to a field and update that piece of information
**Also included**
This PR also includes:
- The abstraction of the pagination …
=> Add strategic action summary page

cypress/integration/strategic_action_summary_spec.js, run_functional_tests.sh
This PR fixes a bug with the github action which runs tests against a PR. 
Previously, the exit code from cypress (i.e the number of tests failing from the functional test suite) was not being returned from the `run_functional_tests.sh` script. This was because the status code of the the if statement was instead being returned. 
I have added the exit code from the cypress tests to a variable and then call exit with that variable at the bottom of the file. 
As a PR with failing tests cannot be merged, I have also fixed two failing tests in the `supply_chain_summary_spec.js` which had been merged into main due to the bug in the script.
**Example**
An example of the tests successfully failing can be found in this [action run](https://github.com/uktrade/defend-data-capture/actions/runs/7893222 …
=> Fix functional test script bug & failing tests

README.md, defend_data_capture/defend_data_capture/urls.py, defend_data_capture/supply_chains/test/test_views.py, defend_data_capture/supply_chains/views.py
This PR refactors the index view - now `HomePageView` - to be class-based rather than a function, to keep consistency between the views.
I also:
- noticed I hadn't previously added a test to make sure that the annotation on the supply_chain queryset is present, so have added an extra assertion to one of the homepage unit tests. 
- reformatted the docstrings of the homepage unit tests to be in line with PEP guidelines
- Corrected the `cy.injectAxe` command in the Readme, as it incorrectly showed `cy.injectA11y()`
=> Refactor index view to be class based

cypress/integration/sc_summary_spec.js, cypress/integration/strategic_action_summary_spec.js, cypress/integration/task_complete_spec.js, cypress/integration/task_list_spec.js, defend_data_capture/supply_chains/templates/sc_summary.html, defend_data_capture/supply_chains/templates/strategic_action_summary.html, defend_data_capture/supply_chains/templates/task_complete.html, defend_data_capture/supply_chains/templates/task_list.html
This PR makes the breadcrumbs structure on the existing pages consistent.
It also:
- updates all tests to check the links of breadcrumbs
- adds the `aria-current="page"` attribute to final breadcrumbs
- makes all final breadcrumbs link to the url of the page, rather than `#`.
**Breadcrumb structure:**
Home(index) > [Supply chain name](task list) > ...
The breadcrumbs of existing pages are now as follows:
- Task list
- Complete page (after submitting update for a supply chain)
- Strategic action summary page
- Supply chain summary page
=> Make breadcrumbs consistent across pages

package-lock.json, package.json
This PR  updates the `css-loader` package to address [this vulnerability issue](https://github.com/uktrade/defend-data-capture/security/dependabot/package-lock.json/postcss/open) raised on the repo.
It also fixes the path used in the `npm run clean` command, which clears the webpack_bundles folder to remove old bundles.
=> Update css-loader package & correct 'clean' npm script

.github/workflows/run-tests.yaml, defend_data_capture/accounts/models.py, defend_data_capture/defend_data_capture/settings.py, defend_data_capture/defend_data_capture/urls.py, defend_data_capture/supply_chains/admin.py, defend_data_capture/supply_chains/models.py, defend_data_capture/supply_chains/templates/base.html, defend_data_capture/supply_chains/test/test_admin.py
This PR creates a django admin instance for the application.
**Configuring display of objects**
From feedback we had from future admin users on how they identify different objects, I have configured the appropriate values to appear in the list view for each model. Also, in order for the objects to be easily recognisable, I have added `__str__` methods to models which didn't have them.
**Logging into admin**
To avoid the need for admin users to have two sets of login details, I have overridden the `login()` method for the admin site. 
If a user is already authenticated (via SSO) and they are marked as `is_staff=True` they will be able to access the admin index page. If either of these are not true, they will be redirected to the app's index url, where if they're unauthenticated they will …
=> Create django admin

cypress/integration/home_page_spec.js, cypress/integration/task_list_spec.js, cypress/support/commands.js, defend_data_capture/assets/stylesheets/application.scss, defend_data_capture/scripts/get_last_working_day_this_month.py, defend_data_capture/supply_chains/templates/base.html, defend_data_capture/supply_chains/templates/index.html, defend_data_capture/supply_chains/templates/task_list.html, get_last_working_day_this_month.py
This PR:
- removes references to features not yet ready for release - the data visualisation tool and the supply chain/strategic action summary pages
- updates the font and header in-line with non gov.uk hosted services - removing the GOV UK logo and making the font Arial
- updates the homepage spec to better test the content of the page - the deadline and the description paragraph
Given that the deadline changes dynamically based on the last working day of the current month, I have added a script which calls the util `get_last_working_day_of_a_month`. This is then called within a new custom cypress command.
=> Update content and styling

requirements.txt, update_supply_chain_information/config/settings.py, update_supply_chain_information/supply_chains/test/test_middleware.py
This PR adds configuration to enable Application Performance Monitoring via Elastic APM. This is one of the points in the 'Operations' section of the [Go live checklist](https://readme.trade.gov.uk/docs/procedures/1st-go-live.html#operations). This allows for monitoring of the application within ELK.
I have deployed this branch on the dev environment and you can see the monitoring dashboard [here in ELK](https://elk.uktrade.digital/app/apm/services/update-supply-chain-information/overview?rangeFrom=now-24h&rangeTo=now&latencyAggregationType=avg) - request access from SRE if needed.
I have also added the appropriate environment variables to dev, staging and production areas of [Vault](https://vault.ci.uktrade.digital/ui/vault/secrets/dit%2Fsupply-chain-resilience/list/update-supply-chain-in …
=> Setup application performance monitoring

Makefile, run_functional_tests.sh, update_supply_chain_information/supply_chains/management/commands/datafixup.py, update_supply_chain_information/supply_chains/test/test_fixture_fixup.py
**Changes**
- Re-enable _datafixup_ tests
- Ask for confirmation while fixing data  using _datafixup_
- To alleviate testDB related over-rides to Django's internal working, using dev-server/dev-db for running functional tests.
- Reset DB before and after running functional tests
- Disable TTY for _exec_ commands within docker container(to work in GHA)
=> RT-305: Fix/enable tests

update_supply_chain_information/supply_chains/templates/base.html, update_supply_chain_information/supply_chains/templatetags/supply_chain_filters.py
This PR adds the `<script>` and `<noscript>` tags recommended by the performance analysis team to the head and body of the base template. This will allow the app to send events to google tag manager.
As the auth string for google tag manager is different for each environment (and there isn't one for production), I have made it an environment variable called `GTM_AUTH_STRING`.
To allow the base template to access this env var, I've created a custom template filter which will provide the value for a given environment variable.
=> Add scripts for google tag manager

update_supply_chain_information/accounts/models.py
**Purpose of PR**
As part of writing documentation for the project to be supported out of hours, I noticed that when running our `manage.py createsuperuser` command in the terminal, it raised the error that an email wasn't provided for the user.
This PR sets the `REQUIRED_FIELDS` attribute on the User model, which determines what fields are requested when the `createsuperuser` command is run. [Docs here](https://docs.djangoproject.com/en/3.2/topics/auth/customizing/#django.contrib.auth.models.CustomUser.REQUIRED_FIELDS).
**To test**
- Pull branch and run `python update_supply_chain_information/manage.py createsuperuser`
- You should be asked for an sso_email_user_id, email, first_name, last_name and password
=> Set required fields for createsuperuser command

cypress/integration/monthly_update_forms_no_completion_date_spec.js, cypress/integration/monthly_update_forms_with_completion_date_spec.js, cypress/support/commands.js, update_supply_chain_information/supply_chains/templates/supply_chains/monthly_update_form_base.html, update_supply_chain_information/supply_chains/templates/supply_chains/monthly_update_summary.html
This PR updates the header of the monthly update pages to show 'Monthly update for [strategic action name]'.
In order to update the functional tests, the PR updates the custom cypress command `cy.monthlyUpdatePageHeader` to accept an argument (the name of a strategic action).
**New header**
=> Display action name in monthly update page headers

package-lock.json, package.json
This PR replaces the node sass library with the dart sass one, as node sass is now deprecated.
This will fix a high severity security vulnerability in a dependency of node sass.
=> Replace node sass with dart sass

cypress/fixtures/govDepartment.json, cypress/fixtures/supplyChains.json, cypress/fixtures/user.json, cypress/integration/access_denied_spec.js, update_supply_chain_information/supply_chains/templates/403.html, update_supply_chain_information/supply_chains/templates/base.html, update_supply_chain_information/supply_chains/templates/task_complete.html, update_supply_chain_information/supply_chains/templatetags/supply_chain_tags.py
This PR creates a custom access denied page, returned whenever the `PermissionDenied` exception is raised. 
Django automatically renders a template with the name `403.html` (if it exists) when `PermissionDenied` is raised.
This page will be shown if a user tries to access a URL not related to an object linked to their gov department - e.g. a supply chain their department isn't responsible for.
In order to feed the feedback email addresses to the `mailto:` link in the 403 template, I have added a template tag which will return the email addresses of all users with `receive_feedback_emails` as True, as a comma separated string.
**Access denied page**
=> Add custom access denied page

cypress/integration/access_denied_spec.js, cypress/integration/home_page_spec.js, run_functional_tests.sh, update_supply_chain_information/assets/stylesheets/application.scss, update_supply_chain_information/sample.env, update_supply_chain_information/supply_chains/templates/403.html, update_supply_chain_information/supply_chains/templates/base.html
This PR makes two changes to the BETA phase banner in the base template:
1. Adds a mailto link to 'feedback' which will open an email to a group email address with users with `receive_email_feedback` as True bcc'd.
2. Vertically centres the text in the banner (caused by an unneeded <span>)
It updates the feedback link in the 403 template to create the same email (group email in 'to' field, with admin users bcc'd)
It also removes the custom class `app-phase-banner-content` which is no longer needed (left over from when there was an additional link in the right of the banner).
**Updated banner**
=> Add feedback link & fix alignment in BETA banner

cypress/integration/home_page_spec.js, update_supply_chain_information/supply_chains/templates/index.html
This PR makes two fixes to content on the homepage:
1. It pluralises 'supply chain' only when there are more than 1 incomplete supply chains for that department
2. It moves the sentence 'All your supply chains are complete...' to a paragraph rather than a bullet point
**When all complete**
**When just 1 supply chain**
**When more than 1 supply chain**
=> Fix homepage content

update_supply_chain_information/supply_chains/test/test_tasklist_view.py, update_supply_chain_information/supply_chains/test/test_views.py, update_supply_chain_information/supply_chains/views.py
This PR makes two fixes:
1. Filters out archived supply chains from the home page view
2. Filters out archived strategic actions from the task list view
I have also added a test for each of these scenarios to the relevant files.
In the `SCTaskListView` I have also filtered out archived strategic actions when calculating `self.ready_to_submit_updates` and `self.submitted_only_updates`. 
This means that the numbers displayed in `x out of x strategic actions are not ready to submit` in the template would remain correct even if an update was given for an action since the last deadline, but that action was then archived (and therefore would no longer appear in the task list)
=> Filter out archived supply chains/strategic actions from views

update_supply_chain_information/supply_chains/test/test_views.py, update_supply_chain_information/supply_chains/views.py
HomePage now factors in supply chain with active strategic actions while building summary data
**Changes**
- Update HomePage _get_context_data_ to count SCs with active SAs
- Tests
**Screenshots**
=> RT-349: Fix homepage summary

update_supply_chain_information/supply_chains/test/test_taskcomplete_view.py, update_supply_chain_information/supply_chains/views.py
Yet another occurrence of incorrect summary message when archived SC is involved.
Applying the same fix to add a filter to exclude archived SC.
**Note**
As its a minor bug w/o any side affects, target branch is _develop_ intended for next release.
=> RT-350: Exclude archived SC within SCCompleteView

package.json
Move to node 14.17.1 as the current runtime is dropped from the CF supported versions list 
https://github.com/cloudfoundry/nodejs-buildpack/issues/330
=> RT-352: Move to next supported version of node to keep up with CF release 1.7.55

update_supply_chain_information/supply_chains/test/test_views.py, update_supply_chain_information/supply_chains/views.py
SAUs weren't saving the user that created them in their `user` field.
=> RT-415: Ensure the user is added to a Strategic Action Update when they start one

update_supply_chain_information/activity_stream/models.py, update_supply_chain_information/activity_stream/pagination.py, update_supply_chain_information/activity_stream/test/test_pagination.py
Some models have many instances with identical values for `last_modified`. The `activity_stream` pagination depends on ordering by that field. As the instances are unordered within the ordering by `last_modified`, it becomes possible for any given instance to appear on multiple pages, or not to appear on any page.
This can be addressed by adding `id` as a second-level ordering.
=> RT-434: Fix/activity stream data loss

update_supply_chain_information/action_progress/templates/includes/action_info.html, update_supply_chain_information/action_progress/templates/includes/monthly_update_details.html
Only change to decrease the font of _notes_ fields to 16 pixels
=> RT-484: Decrease the font size for notes within SAP details

update_supply_chain_information/activity_stream/models.py, update_supply_chain_information/activity_stream/test/conftest.py, update_supply_chain_information/activity_stream/test/test_querysets.py
The one-to-one relationship between `ScenarioAssessment` and `SupplyChain` was not represented in the activity stream. These commits adds support and tests.
=> RT-566: Fix: ScenarioAssessment one-to-one fields in activity stream.

cypress/integration/sap_details_spec.js, cypress/integration/scd_info_spec.js, update_supply_chain_information/action_progress/templates/action_progress_details.html, update_supply_chain_information/chain_details/templates/chain_details_info.html, update_supply_chain_information/config/settings.py, update_supply_chain_information/sample.env, update_supply_chain_information/supply_chains/templates/base.html, update_supply_chain_information/supply_chains/templates/index.html, update_supply_chain_information/supply_chains/templatetags/supply_chain_tags.py
Include country information (configured in environment) and strategic… action progress Quicksight links.
This needs
```
QUICKSIGHT_COUNTRIES_DASHBOARD_URL=https://data.trade.gov.uk/visualisations/link/2ade7245-2629-4dff-a2ff-d700b5a74807
``` in .env, otherwise the links will be to `about:blank`.
=> RT-579: QuickSight link taken from Vault/environment.

update_supply_chain_information/supply_chains/models.py, update_supply_chain_information/supply_chains/test/test_scenario_assessment_versioning.py
Just a save method to add a meaningful comment to the version, and a couple of tests. Also, `Optimise imports` found some stray ones on `supply_chains.models` and removed them.
=> RT-534: Add revision tracking to scenario assessments.
